version: "3.7"

services:
    postgres:
        image: postgres        
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASS=z2frk93j1
            - POSTGRES_DB=ariapet
        volumes:
            - pgdata:/data/postgres
        network_mode: host
    app:
        build: .
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        network_mode: host
volumes:
    pgdata:
        driver: local